namespace Xeno.Tests;

[RegisterComponent(typeof(Component1))]
[RegisterComponent(typeof(Component2))]
[RegisterComponent(typeof(Component3))]
[RegisterComponent(typeof(Component4))]
[RegisterComponent(typeof(Component5))]
[RegisterComponent(typeof(ComponentA))]
[RegisterComponent(typeof(ComponentB))]
[RegisterComponent(typeof(LargeComponent))]
[RegisterComponent(typeof(RuntimeReferenceComponent))]
[RegisterComponent(typeof(Component_1))]
[RegisterComponent(typeof(Component_2))]
[RegisterComponent(typeof(Component_3))]
[RegisterComponent(typeof(Component_4))]
[RegisterComponent(typeof(Component_5))]
[RegisterComponent(typeof(Component_6))]
[RegisterComponent(typeof(Component_7))]
[RegisterComponent(typeof(Component_8))]
[RegisterComponent(typeof(Component_9))]
[RegisterComponent(typeof(Component_10))]
[RegisterComponent(typeof(Component_11))]
[RegisterComponent(typeof(Component_12))]
[RegisterComponent(typeof(Component_13))]
[RegisterComponent(typeof(Component_14))]
[RegisterComponent(typeof(Component_15))]
[RegisterComponent(typeof(Component_16))]
[RegisterComponent(typeof(Component_17))]
[RegisterComponent(typeof(Component_18))]
[RegisterComponent(typeof(Component_19))]
[RegisterComponent(typeof(Component_20))]
[RegisterComponent(typeof(Component_21))]
[RegisterComponent(typeof(Component_22))]
[RegisterComponent(typeof(Component_23))]
[RegisterComponent(typeof(Component_24))]
[RegisterComponent(typeof(Component_25))]
[RegisterComponent(typeof(Component_26))]
[RegisterComponent(typeof(Component_27))]
[RegisterComponent(typeof(Component_28))]
[RegisterComponent(typeof(Component_29))]
[RegisterComponent(typeof(Component_30))]
[RegisterComponent(typeof(Component_31))]
[RegisterComponent(typeof(Component_32))]
[RegisterComponent(typeof(Component_33))]
[RegisterComponent(typeof(Component_34))]
[RegisterComponent(typeof(Component_35))]
[RegisterComponent(typeof(Component_36))]
[RegisterComponent(typeof(Component_37))]
[RegisterComponent(typeof(Component_38))]
[RegisterComponent(typeof(Component_39))]
[RegisterComponent(typeof(Component_40))]
[RegisterComponent(typeof(Component_41))]
[RegisterComponent(typeof(Component_42))]
[RegisterComponent(typeof(Component_43))]
[RegisterComponent(typeof(Component_44))]
[RegisterComponent(typeof(Component_45))]
[RegisterComponent(typeof(Component_46))]
[RegisterComponent(typeof(Component_47))]
[RegisterComponent(typeof(Component_48))]
[RegisterComponent(typeof(Component_49))]
[RegisterComponent(typeof(Component_50))]
[RegisterComponent(typeof(Component_51))]
[RegisterComponent(typeof(Component_52))]
[RegisterComponent(typeof(Component_53))]
[RegisterComponent(typeof(Component_54))]
[RegisterComponent(typeof(Component_55))]
[RegisterComponent(typeof(Component_56))]
[RegisterComponent(typeof(Component_57))]
[RegisterComponent(typeof(Component_58))]
[RegisterComponent(typeof(Component_59))]
[RegisterComponent(typeof(Component_60))]
[RegisterComponent(typeof(Component_61))]
[RegisterComponent(typeof(Component_62))]
[RegisterComponent(typeof(Component_63))]
[RegisterComponent(typeof(Component_64))]
[RegisterComponent(typeof(Component_65))]
[RegisterComponent(typeof(Component_66))]
[RegisterComponent(typeof(Component_67))]
[RegisterComponent(typeof(Component_68))]
[RegisterComponent(typeof(Component_69))]
[RegisterComponent(typeof(Component_70))]
[RegisterComponent(typeof(Component_71))]
[RegisterComponent(typeof(Component_72))]
[RegisterComponent(typeof(Component_73))]
[RegisterComponent(typeof(Component_74))]
[RegisterComponent(typeof(Component_75))]
[RegisterComponent(typeof(Component_76))]
[RegisterComponent(typeof(Component_77))]
[RegisterComponent(typeof(Component_78))]
[RegisterComponent(typeof(Component_79))]
[RegisterComponent(typeof(Component_80))]
[RegisterComponent(typeof(Component_81))]
[RegisterComponent(typeof(Component_82))]
[RegisterComponent(typeof(Component_83))]
[RegisterComponent(typeof(Component_84))]
[RegisterComponent(typeof(Component_85))]
[RegisterComponent(typeof(Component_86))]
[RegisterComponent(typeof(Component_87))]
[RegisterComponent(typeof(Component_88))]
[RegisterComponent(typeof(Component_89))]
[RegisterComponent(typeof(Component_90))]
[RegisterComponent(typeof(Component_91))]
[RegisterComponent(typeof(Component_92))]
[RegisterComponent(typeof(Component_93))]
[RegisterComponent(typeof(Component_94))]
[RegisterComponent(typeof(Component_95))]
[RegisterComponent(typeof(Component_96))]
[RegisterComponent(typeof(Component_97))]
[RegisterComponent(typeof(Component_98))]
[RegisterComponent(typeof(Component_99))]
[RegisterComponent(typeof(Component_100))]
public partial class GeneratedTestWorld : World {
    public partial Entity CreateEntity(in Component1 component1, in Component2 component2);
    public partial Entity CreateEntity(in Component1 component1, in Component2 component2, in Component3 component3);
    public partial Entity CreateEntity(in Component1 component1, in Component2 component2, in Component3 component3, in Component4 component4);
    public partial Entity CreateEntity(in ComponentA componentA, in ComponentB componentB);
    public partial Entity CreateEntity(in Component_1 component1, in Component_2 component2, in Component_3 component3);
    public partial Entity CreateEntity(in Component_4 component4, in Component_5 component5, in Component_6 component6, in Component_7 component7);
}

internal static class TestWorlds {
    public static GeneratedTestWorld Create(string name) => new(name);

    public static GeneratedTestWorld Get(string name) {
        if (!Worlds.TryGet(name, out var world))
            throw new global::System.InvalidOperationException($"World '{name}' was not found.");
        return (GeneratedTestWorld)world;
    }
}
